<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Menu;

class MenuSeeder extends Seeder
{
    public function run(): void
    {
        // Hapus semua data lama
        Menu::truncate();

        $menus = [
            [
                'text' => 'Beranda',
                'icon' => 'ti ti-home',
                'url' => 'dashboard',
                'type' => 'route',
                'order' => 0,
                'is_active' => true,
            ],
            [
                'text' => 'Menu',
                'icon' => 'ti ti-home',
                'url' => '/menus',
                'type' => 'url',
                'order' => 1,
                'is_active' => true,
                'permission_name' => 'lihat daftar menu',
            ],
            [
                'text' => 'Akun',
                'icon' => 'ti ti-user-circle',
                'url' => '#',
                'type' => 'url',
                'order' => 2,
                'is_active' => true,
                'permission_name' => 'lihat daftar user',
                'children' => [
                    [
                        'text' => 'Manajemen User',
                        'icon' => 'ti ti-user-circle',
                        'url' => '/users',
                        'type' => 'url',
                        'order' => 0,
                        'is_active' => true,
                        'permission_name' => 'lihat daftar user',
                    ],
                    [
                        'text' => 'Manajemen Role',
                        'icon' => 'ti ti-user-check',
                        'url' => '/roles',
                        'type' => 'url',
                        'order' => 1,
                        'is_active' => true,
                        'permission_name' => 'lihat daftar role',
                    ],
                    [
                        'text' => 'Manajemen Akun',
                        'icon' => 'ti ti-user',
                        'url' => '/accounts',
                        'type' => 'url',
                        'order' => 2,
                        'is_active' => true,
                        'permission_name' => 'kelola akun',
                    ],
                ],
            ],
            [
                'text' => 'SDM',
                'icon' => 'ti ti-briefcase',
                'url' => '#',
                'type' => 'url',
                'order' => 3,
                'is_active' => true,
                'permission_name' => 'lihat daftar karyawan|lihat data karyawan',
                'children' => [
                    [
                        'text' => 'Data Karyawan',
                        'icon' => 'ti ti-id-badge',
                        'url' => '/employees',
                        'type' => 'url',
                        'order' => 0,
                        'is_active' => true,
                        'permission_name' => 'lihat daftar karyawan|lihat data karyawan',
                    ],
                    [
                        'text' => 'Absensi',
                        'icon' => 'ti ti-article',
                        'url' => '/licenses',
                        'type' => 'url',
                        'order' => 1,
                        'is_active' => true,
                        'permission_name' => 'lihat daftar absensi',
                    ],
                    [
                        'text' => 'Pelatihan',
                        'icon' => 'ti ti-article',
                        'url' => '/license_holders',
                        'type' => 'url',
                        'order' => 2,
                        'is_active' => true,
                        'permission_name' => 'lihat daftar pelatihan',
                    ],
                    [
                        'text' => 'Penilaian Kinerja',
                        'icon' => 'ti ti-article',
                        'url' => '/accounting',
                        'type' => 'url',
                        'order' => 3,
                        'is_active' => true,
                        'permission_name' => 'lihat daftar penilaian kinerja',
                    ],
                ],
            ],
            [
                'text' => 'Recruitment',
                'icon' => 'ti ti-users',
                'url' => '#',
                'type' => 'url',
                'order' => 4,
                'is_active' => true,
                'permission_name' => 'lihat daftar recruitment',
                'children' => [
                    [
                        'text' => 'Template Lowongan Kerja',
                        'icon' => 'ti ti-article',
                        'url' => '/recruitment',
                        'type' => 'url',
                        'order' => 0,
                        'is_active' => true,
                        'permission_name' => 'lihat daftar recruitment',
                    ],
                ],
            ],
            [
                'text' => 'Customer',
                'icon' => 'ti ti-building-bank',
                'url' => '#',
                'type' => 'url',
                'order' => 5,
                'is_active' => true,
                'permission_name' => 'lihat daftar customer',
                'children' => [
                    [
                        'text' => 'Daftar Customer',
                        'icon' => 'ti ti-book',
                        'url' => '/customer',
                        'type' => 'url',
                        'order' => 0,
                        'is_active' => true,
                        'permission_name' => 'lihat daftar customer',
                    ],
                    [
                        'text' => 'Edit Profile',
                        'icon' => 'ti ti-notebook',
                        'url' => '/customer/profile',
                        'type' => 'url',
                        'order' => 1,
                        'is_active' => true,
                        'permission_name' => 'ubah data customer',
                    ],
                    [
                        'text' => 'Riwayat Transaksi',
                        'icon' => 'ti ti-notebook',
                        'url' => '/customer/history',
                        'type' => 'url',
                        'order' => 2,
                        'is_active' => true,
                        'permission_name' => 'riwayat transaksi customer',
                    ],
                ],
            ],
                        [
                'text' => 'Affiliator',
                'icon' => 'ti ti-building-bank',
                'url' => '#',
                'type' => 'url',
                'order' => 6,
                'is_active' => true,
                'permission_name' => 'lihat daftar affiliator',
                'children' => [
                    [
                        'text' => 'Daftar Affiliator',
                        'icon' => 'ti ti-book',
                        'url' => '/affiliator',
                        'type' => 'url',
                        'order' => 0,
                        'is_active' => true,
                        'permission_name' => 'lihat daftar affiliator',
                    ],
                    [
                        'text' => 'Riwayat Performa',
                        'icon' => 'ti ti-notebook',
                        'url' => '/affiliator/history',
                        'type' => 'url',
                        'order' => 1,
                        'is_active' => true,
                        'permission_name' => 'riwayat performa affiliator',
                    ],
                ],
            ],
            [
                'text' => 'Supplier',
                'icon' => 'ti ti-building-bank',
                'url' => '#',
                'type' => 'url',
                'order' => 7,
                'is_active' => true,
                'permission_name' => 'lihat daftar supplier',
                'children' => [
                    [
                        'text' => 'Daftar Supplier',
                        'icon' => 'ti ti-book',
                        'url' => '/supplier',
                        'type' => 'url',
                        'order' => 0,
                        'is_active' => true,
                        'permission_name' => 'lihat daftar supplier',
                    ],
                    [
                        'text' => 'Riwayat Pembelian',
                        'icon' => 'ti ti-notebook',
                        'url' => '/history/supplier',
                        'type' => 'url',
                        'order' => 1,
                        'is_active' => true,
                        'permission_name' => 'riwayat pembelian supplier',
                    ],
                ],
            ],
            [
                'text' => 'Investor',
                'icon' => 'ti ti-building-bank',
                'url' => '#',
                'type' => 'url',
                'order' => 8,
                'is_active' => true,
                'permission_name' => 'lihat daftar investor',
                'children' => [
                    [
                        'text' => 'Daftar Investor',
                        'icon' => 'ti ti-book',
                        'url' => '/investor',
                        'type' => 'url',
                        'order' => 0,
                        'is_active' => true,
                        'permission_name' => 'lihat daftar investor',
                    ],
                    [
                        'text' => 'Informasi Kepemilikan',
                        'icon' => 'ti ti-notebook',
                        'url' => '/investor/modal',
                        'type' => 'url',
                        'order' => 1,
                        'is_active' => true,
                        'permission_name' => 'saham investor',
                    ],
                ],
            ],
            [
                'text' => 'Tukang',
                'icon' => 'ti ti-building-bank',
                'url' => '#',
                'type' => 'url',
                'order' => 9,
                'is_active' => true,
                'permission_name' => 'lihat daftar tukang',
                'children' => [
                    [
                        'text' => 'Daftar Tukang',
                        'icon' => 'ti ti-book',
                        'url' => '/worker',
                        'type' => 'url',
                        'order' => 0,
                        'is_active' => true,
                        'permission_name' => 'lihat daftar tukang',
                    ],
                    // [
                    //     'text' => 'Dokumen',
                    //     'icon' => 'ti ti-notebook',
                    //     'url' => 'worker/document',
                    //     'type' => 'url',
                    //     'order' => 1,
                    //     'is_active' => true,
                    //     'permission_name' => 'Ubah data customer',
                    // ],
                    [
                        'text' => 'Riwayat Penggajian',
                        'icon' => 'ti ti-notebook',
                        'url' => '/worker/history',
                        'type' => 'url',
                        'order' => 2,
                        'is_active' => true,
                        'permission_name' => 'riwayat penggajian tukang',
                    ],
                ],
            ],
            [
                'text' => 'Kontraktor',
                'icon' => 'ti ti-building-bank',
                'url' => '#',
                'type' => 'url',
                'order' => 10,
                'is_active' => true,
                'permission_name' => 'lihat daftar kontraktor',
                'children' => [
                    [
                        'text' => 'Daftar Kontraktor',
                        'icon' => 'ti ti-book',
                        'url' => '/contractor',
                        'type' => 'url',
                        'order' => 0,
                        'is_active' => true,
                        'permission_name' => 'lihat daftar kontraktor',
                    ],
                    [
                        'text' => 'Riwayat Transaksi Customer',
                        'icon' => 'ti ti-notebook',
                        'url' => '/contractor/history',
                        'type' => 'url',
                        'order' => 1,
                        'is_active' => true,
                        'permission_name' => 'riwayat penggajian kontraktor',
                    ],
                ],
            ],
            [
                'text' => 'Data Gudang',
                'icon' => 'ti ti-hammer',
                'url' => '#',
                'type' => 'url',
                'order' => 11,
                'is_active' => true,
                'permission_name' => 'lihat daftar gudang',
                'children' => [
                    [
                        'text' => 'Daftar Gudang',
                        'icon' => 'ti ti-building-warehouse',
                        'url' => '/warehouse',
                        'type' => 'url',
                        'order' => 0,
                        'is_active' => true,
                        'permission_name' => 'lihat daftar gudang',
                    ],
                    [
                        'text' => 'Riwayat Gudang',
                        'icon' => 'ti ti-package',
                        'url' => '/wareheouse/history',
                        'type' => 'url',
                        'order' => 1,
                        'is_active' => true,
                        'permission_name' => 'riwayat transaksi gudang',
                    ],
                ],
            ],
            [
                'text' => 'Data Produk',
                'icon' => 'ti ti-hammer',
                'url' => '#',
                'type' => 'url',
                'order' => 12,
                'is_active' => true,
                'permission_name' => 'lihat daftar produk',
                'children' => [
                    [
                        'text' => 'Daftar Produk',
                        'icon' => 'ti ti-building-warehouse',
                        'url' => '/product',
                        'type' => 'url',
                        'order' => 0,
                        'is_active' => true,
                        'permission_name' => 'lihat daftar produk',
                    ],
                    [
                        'text' => 'Riwayat Transaksi Produk',
                        'icon' => 'ti ti-package',
                        'url' => '/product/history',
                        'type' => 'url',
                        'order' => 1,
                        'is_active' => true,
                        'permission_name' => 'riwayat pembelian produk',
                    ],
                ],
            ],
            [
                'text' => 'Finance',
                'icon' => 'ti ti-building-bank',
                'url' => '#',
                'type' => 'url',
                'order' => 16,
                'is_active' => true,
                'permission_name' => 'lihat akun-akuntansi',
                'children' => [
                    [
                        'text' => 'Daftar Akun Akuntansi',
                        'icon' => 'ti ti-book',
                        'url' => '/accounting/accounts',
                        'type' => 'url',
                        'order' => 0,
                        'is_active' => true,
                        'permission_name' => 'lihat akun-akuntansi',
                    ],
                    [
                        'text' => 'Jurnal',
                        'icon' => 'ti ti-notebook',
                        'url' => '/accounting/journals',
                        'type' => 'url',
                        'order' => 1,
                        'is_active' => true,
                        'permission_name' => 'lihat jurnal',
                    ],
                ],
            ],
            [
                'text' => 'Proyek',
                'icon' => 'ti ti-building-arch',
                'url' => '#',
                'type' => 'url',
                'order' => 15,
                'is_active' => true,
                'permission_name' => 'lihat daftar proyek',
                'children' => [
                    [
                        'text' => 'Daftar Proyek',
                        'icon' => 'ti ti-building-community',
                        'url' => '/project',
                        'type' => 'url',
                        'order' => 0,
                        'is_active' => true,
                        'permission_name' => 'lihat daftar proyek',
                    ],
                    [
                        'text' => 'RAB Proyek',
                        'icon' => 'ti ti-calculator',
                        'url' => '/project/rab',
                        'type' => 'url',
                        'order' => 1,
                        'is_active' => true,
                        'permission_name' => 'lihat data rab',
                    ],
                ],
            ],
            [
                'text' => 'Dokumen',
                'icon' => 'ti ti-files',
                'url' => '#',
                'type' => 'url',
                'order' => 13,
                'is_active' => true,
                'permission_name' => 'lihat daftar dokumen',
                'children' => [
                    [
                        'text' => 'Daftar Dokumen',
                        'icon' => 'ti ti-file-text',
                        'url' => '/document',
                        'type' => 'url',
                        'order' => 0,
                        'is_active' => true,
                        'permission_name' => 'lihat daftar dokumen',
                    ],
                ],
            ],
            [
                'text' => 'Transaksi',
                'icon' => 'ti ti-building-bank',
                'url' => '#',
                'type' => 'url',
                'order' => 14,
                'is_active' => true,
                'permission_name' => 'riwayat pembelian produk',
                'children' => [
                    [
                        'text' => 'Pembelian Produk',
                        'icon' => 'ti ti-book',
                        'url' => '/product/pembelian',
                        'type' => 'url',
                        'order' => 0,
                        'is_active' => true,
                        'permission_name' => 'riwayat pembelian produk',
                    ],
                    [
                        'text' => 'Penjualan Produk',
                        'icon' => 'ti ti-notebook',
                        'url' => '/product/penjualan',
                        'type' => 'url',
                        'order' => 1,
                        'is_active' => true,
                        'permission_name' => 'riwayat penjualan produk',
                    ],
                ],
            ],
        ];

        foreach ($menus as $menuData) {
            $children = $menuData['children'] ?? [];
            unset($menuData['children']);

            $parent = Menu::create($menuData);

            foreach ($children as $childData) {
                $childData['parent_id'] = $parent->id;
                Menu::create($childData);
            }
        }
    }
}
